### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by onehundredfeet** [haxiomic/haxe-threejs-template#8]
Hi,

Cool project.  I get the following when trying to run bundle.js or app.js:

ReferenceError: window is not defined

ReferenceError: window is not defined
    at haxe-threejs-template/node_modules/dat.gui/build/dat.gui.js:1596:31
    at haxe-threejs-template/node_modules/dat.gui/build/dat.gui.js:15:65
    at Object.<anonymous> haxe-threejs-template/node_modules/dat.gui/build/dat.gui.js:18:2)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at /Users/rcleven/git/haxe-threejs-template/bin/app.js:513:21

**Comment by onehundredfeet** [comment]
I'm doing it wrong.
